## The "Simple List" Way

- name: Print the full name of mine.
  ansible.builtin.debug:
    msg: "My name is {{ item }}"
  loop:
    - kiran
    - panchavati


## Dictionary

- name: Print the details.
  ansible.builtin.debug:
    msg: "My total experience in IT industry is {{ item.experience }} years and looking for the {{ item.role1 }} and {{ item.role2 }} positions"
  loop:
    - { experience: '8', role1: 'DevSecOps', role2: 'Solution Architect' }