- name: Install the web server
  ansible.builtin.dnf:
    name: httpd
    state: latest
  when: ansible_facts['os_family'] == "RedHat"
  notify: Restart httpd

- name: Print the IP address
  ansible.builtin.debug:
    msg: "{{ ansible_default_ipv4.address }}"

- name: Print the architecture 
  ansible.builtin.debug:
    msg: "{{ ansible_architecture }}"


- name: Print the process 
  ansible.builtin.debug:
    msg: "{{ ansible_processor }}"
