- name: Install the web server
  ansible.builtin.dnf:
    name: httpd
    state: latest
  when: ansible_facts['os_family'] == "RedHat"
  notify: Restart httpd

- name: Print the facts
  ansible.builtin.debug:
    msg: "{{ ansible_default_ipv4.address }}"
